export enum QueryKey {
	Workspaces = 'workspaces',
	Workspaces_Public = 'workspaces_public',
	Workspace = 'workspace',
	Nodes = 'nodes',
	Node = 'node',
	Edges = 'edges',
	Edge = 'edge',
	Files = 'files',
}

export const ROUTES = {
	home: '/',
	workspace: '/workspace',
	filesLibrary: '/files-library',
};

export enum HeaderKeysEnum {
	'A-IM' = 'A-IM',
	'Accept' = 'Accept',
	'Accept-Charset' = 'Accept-Charset',
	'Accept-Datetime' = 'Accept-Datetime',
	'Accept-Encoding' = 'Accept-Encoding',
	'Accept-Language' = 'Accept-Language',
	'Access-Control-Request-Headers' = 'Access-Control-Request-Headers',
	'Access-Control-Request-Method' = 'Access-Control-Request-Method',
	'Authorization' = 'Authorization',
	'Cache-Control' = 'Cache-Control',
	'Connection' = 'Connection',
	'Content-Length' = 'Content-Length',
	'Content-Type' = 'Content-Type',
	'Cookie' = 'Cookie',
	'Date' = 'Date',
	'Expect' = 'Expect',
	'Forwarded' = 'Forwarded',
	'From' = 'From',
	'Host' = 'Host',
	'If-Match' = 'If-Match',
	'If-Modified-Since' = 'If-Modified-Since',
	'If-None-Match' = 'If-None-Match',
	'If-Range' = 'If-Range',
	'If-Unmodified-Since' = 'If-Unmodified-Since',
	'Max-Forwards' = 'Max-Forwards',
	'Origin' = 'Origin',
	'Pragma' = 'Pragma',
	'Proxy-Authorization' = 'Proxy-Authorization',
	'Range' = 'Range',
	'Referer' = 'Referer',
	'TE' = 'TE',
	'Trailer' = 'Trailer',
	'Transfer-Encoding' = 'Transfer-Encoding',
	'Upgrade' = 'Upgrade',
	'User-Agent' = 'User-Agent',
	'Via' = 'Via',
	'Warning' = 'Warning',
}
